name: CI

on: [push, pull_request]

jobs:
  build_ubuntu_21:
    runs-on: ubuntu-latest
    container: ubuntu:impish-20220316

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt install -y clang
          apt install -y cmake extra-cmake-modules gettext libfmt-dev
          apt install -y fcitx5=5.0.5-1ubuntu2 libfcitx5core-dev=5.0.5-1ubuntu2 libfcitx5config-dev=5.0.5-1ubuntu2 libfcitx5utils-dev=5.0.5-1ubuntu2
      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake ../ -DCMAKE_INSTALL_PREFIX=/usr
          make -j
          cd ../
          mkdir -p src/Engine/build
          cd src/Engine/build
          cmake ../
          make -j
      - name: Test
        run: |
          cd build
          make runTest
          cd ../src/Engine/build
          make runMcBopomofoLMLibTest

  build_ubuntu_20:
    runs-on: ubuntu-latest
    container: ubuntu:focal-20220316

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt install -y clang
          apt install -y cmake extra-cmake-modules gettext libfmt-dev
          apt install -y fcitx5 libfcitx5core-dev libfcitx5config-dev libfcitx5utils-dev
      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake ../ -DCMAKE_INSTALL_PREFIX=/usr -DUSE_LEGACY_FCITX5_API=1
          make -j
      - name: Test
        run: |
          cd build
          make runTest

  build_archlinux:
    runs-on: ubuntu-latest
    container: ghcr.io/xatier/arch-dev:latest

    steps:
      - name: Checkout
        run: |
          export HOME=/home/xatier
          cd /home/xatier
          echo "cloning $GITHUB_SERVER_URL/$GITHUB_REPOSITORY into $PWD $GITHUB_SHA"
          git clone "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY"

          cd /home/xatier/fcitx5-mcbopomofo
          git fetch origin "$GITHUB_REF" ||:
          git checkout "$GITHUB_SHA"

      - name: Build
        run: |
          export HOME=/home/xatier
          cd /home/xatier/fcitx5-mcbopomofo/distro/archlinux/
          sudo pacman -Syy
          makepkg -s --noconfirm
