name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:impish-20220316

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt install -y clang
          apt install -y cmake extra-cmake-modules gettext
          apt install -y fcitx5=5.0.5-1ubuntu2 libfcitx5core-dev=5.0.5-1ubuntu2 libfcitx5config-dev=5.0.5-1ubuntu2 libfcitx5utils-dev=5.0.5-1ubuntu2
      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug # use Debug for easy debugging with gdb
          make # or ninja, depending on your system
